name: demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0-36.0.dev

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  flutter_spinkit: ^5.2.1
  device_info_plus: ^10.1.2
  get_ip_address: ^0.0.7
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  geolocator: ^13.0.1
  package_info_plus: ^8.0.2
  smooth_page_indicator: ^1.2.0+3
  easy_debounce: ^2.0.3
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/to/asset-from-package